# Generated by Django 3.2.7 on 2021-09-29 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subIdea', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='validate',
            field=models.BooleanField(default=0),
        ),
    ]
