# Generated by Django 3.2.7 on 2021-09-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subIdea', '0004_alter_post_validate'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ideaDone', models.BooleanField(default=0)),
                ('pocDone', models.BooleanField(default=0)),
                ('socialDone', models.BooleanField(default=0)),
            ],
        ),
    ]
