# Generated by Django 3.1.2 on 2021-10-04 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subIdea', '0009_auto_20210930_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='tasks',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
