# Generated by Django 3.2.7 on 2021-10-13 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='instahandle',
            field=models.CharField(default='', max_length=200),
        ),
    ]
