# Generated by Django 3.2.7 on 2021-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
