# Generated by Django 3.2.9 on 2022-09-03 14:07

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='alcherid',
            field=models.CharField(blank=True, default=users.models.create_new_ref_number, max_length=9, unique=True),
        ),
    ]
