# Generated by Django 2.2.4 on 2021-09-14 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='provider',
            field=models.CharField(default='email', max_length=200),
        ),
    ]
