# Generated by Django 3.2.7 on 2021-10-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='tasks',
            field=models.IntegerField(default=0),
        ),
    ]
