# Generated by Django 3.1.2 on 2021-10-01 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_newuser_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='referrals',
            field=models.IntegerField(default=0),
        ),
    ]
