# Generated by Django 3.2.7 on 2021-10-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_newuser_instahandle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='points',
            field=models.IntegerField(default=50),
        ),
    ]
