# Generated by Django 3.2.9 on 2022-09-09 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220910_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='phone',
            field=models.TextField(blank=True),
        ),
    ]
