# Generated by Django 3.2.9 on 2022-08-13 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='fb_handle',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
