# Generated by Django 3.2.9 on 2022-08-13 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_fb_handle'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='update_status',
            field=models.IntegerField(default=0),
        ),
    ]
