# Generated by Django 3.2.9 on 2022-09-09 21:45

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_newuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='alcherid',
            field=models.TextField(blank=True, default=users.models.create_new_ref_number, unique=True),
        ),
    ]
