# Generated by Django 4.0.4 on 2022-12-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_newuser_alcherid'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='has_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='newuser',
            name='alcherid',
            field=models.TextField(blank=True, default='create_new_ref_number', unique=True),
        ),
    ]
