# Generated by Django 3.2.9 on 2022-08-13 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_update_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='countrycode',
            field=models.CharField(blank=True, default='+91', max_length=3),
        ),
        migrations.AddField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
