# Generated by Django 3.2.9 on 2022-08-13 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220813_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='countrycode',
            field=models.CharField(blank=True, default='+91', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phoneno',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
