# Generated by Django 4.0.4 on 2022-12-13 15:12

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_newuser_has_password_alter_newuser_alcherid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='alcherid',
            field=models.TextField(blank=True, default=users.models.create_new_ref_number, unique=True),
        ),
    ]
