# Generated by Django 3.2.9 on 2022-08-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20220813_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='points',
            field=models.IntegerField(default=250),
        ),
    ]
