# Generated by Django 3.2.9 on 2022-10-21 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newuser_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newuser',
            name='instahandle',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
