# Generated by Django 3.1.2 on 2021-10-03 16:24

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareablePost',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('link_instagram', models.CharField(max_length=500)),
                ('link_facebook', models.CharField(max_length=500)),
                ('is_instagram', models.BooleanField(default=False)),
                ('is_facebook', models.BooleanField(default=False)),
                ('image', models.ImageField(upload_to='')),
                ('caption', models.CharField(max_length=500000)),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
