# Generated by Django 3.1.2 on 2021-10-03 15:40

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ShareablePost',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('link', models.CharField(max_length=500)),
                ('last_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
