# Generated by Django 3.2.7 on 2021-10-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablepost',
            name='image',
            field=models.ImageField(upload_to='image-uploads/'),
        ),
    ]
