# Generated by Django 3.2.9 on 2022-10-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shareablepost',
            name='caption',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
