# Generated by Django 3.2.9 on 2022-08-24 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posturl',
            name='url_id',
            field=models.TextField(blank=True),
        ),
    ]
