# Generated by Django 3.1.2 on 2021-10-04 12:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablepost',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='shareablepost',
            name='caption',
            field=models.CharField(max_length=160),
        ),
    ]
