# Generated by Django 3.2.7 on 2021-10-12 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shareablepost',
            name='likedusers',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='shareablepost',
            name='media_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
