# Generated by Django 3.1.2 on 2021-10-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20211012_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='isread',
            field=models.BooleanField(default=False),
        ),
    ]
