# Generated by Django 3.2.7 on 2021-10-19 03:37

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_notifications_isread'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promotions',
            fields=[
                ('id', models.SlugField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('link', models.CharField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(upload_to='image-uploads/')),
                ('description', models.TextField(blank=True, default='', null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
