# Generated by Django 3.2.8 on 2021-10-05 17:23

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submissions.submission')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('submit_date', models.DateField(default=django.utils.timezone.now)),
            ],
            bases=('submissions.submission',),
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submissions.submission')),
                ('submit_date', models.DateField(default=django.utils.timezone.now)),
            ],
            bases=('submissions.submission',),
        ),
        migrations.CreateModel(
            name='POC',
            fields=[
                ('submission_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='submissions.submission')),
                ('name', models.CharField(max_length=70)),
                ('design', models.CharField(max_length=60)),
                ('college', models.CharField(max_length=90)),
                ('contact', models.CharField(max_length=13)),
                ('submit_date', models.DateField(default=django.utils.timezone.now)),
            ],
            bases=('submissions.submission',),
        ),
    ]
