# Generated by Django 3.2.7 on 2021-10-07 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0003_pocbulk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pocbulk',
            name='csv_file',
            field=models.FileField(upload_to='image-uploads'),
        ),
    ]
