# Generated by Django 3.2.9 on 2022-08-12 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0004_auto_20220812_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Answer',
        ),
    ]
