# Generated by Django 3.2.9 on 2022-08-14 13:34

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('submissions', '0008_auto_20220812_2001'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='submission',
            unique_together={('user', 'quiz')},
        ),
    ]
